### ISSUE TITLE
Lobby name change error

### ISSUE THREAD

**Issue by mert574** [pomle/draw#7]
When I change the lobby name to anything from default random string; lobby is not becoming joinable.

I also tried this:
Copied the first random name, changed it and then tried to connect with both the random and the changed name. Both doesn't work.

Error: Could not connect to peer TEST

    at Peer../node_modules/snex/dist/snex.js.Peer.emitError (snex.js:1694)
    at Peer../node_modules/snex/dist/snex.js.Peer._handleMessage (snex.js:1527)
    at Socket.<anonymous> (snex.js:1434)
    at Socket.emit (snex.js:351)
    at WebSocket._socket.onmessage (snex.js:557)

**Comment by pomle** [comment]
Hey, thanks for the report. Is this reproducible on your end. I followed the instructions and works as expected. Please provide more detail on how often this happens, what you did before etc.

**Comment by mert574** [comment]
Easily reproducible even with clean install. I'm able to reproduce with these steps:

**1.** `git clone https://github.com/pomle/draw.git`
**2.** `cd draw/`, `npm update`, `npm start`

**3.** 2 incognito chrome windows with `ctrl + shift + N`
_Window 1:_ started to host with default random name 'LEPA'
_Window 2:_ Successfully, joined the room named 'LEPA'

**4.** Refreshed both incognito windows.
_Window 1:_ started to host with a lobby name 'test' Says:

> Welcome to the Lobby
> Join the game at
> test

_Window 2:_ Cannot join the room named 'test'. Says:

> Could not connect to peer TEST

_____
Versions
> Chrome: 63.0.3239.132 (64 bit)
> npm: 5.6.0
> node: 8.9.4

**Comment by mert574** [comment]
Found it! the problem is this:
When hosting a lobby, the name has to be uppercase. From joining side it doesn't matter.
 
Forcing uppercase can be the solution.

**Comment by pomle** [comment]
@mert574 great!

I remember this. I uppercased the input when I created random session words.

I think the solution we should try, is normalize it to uppercase when it is sent to the server for peering, but keep it as entered in the client. That way the room name when given can be displayed with picked case, while still be case insensitive when entered.
